# MinIO 分布式文件系统
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  # 自定义域名(非必须)，Nginx配置反向代理转发文件路径
  custom-domain:
  # 默认的桶名称(非必须)，每个微服务有单独的默认存储桶，建议具体聚合层服务覆盖此配置
  default-bucket: default