# 以下文件放Nacos Config，Data ID：learn-ums.yaml，Group：LEARN_GROUP
server:
  port: 8801

dubbo:
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.meeleet.learn.ums.rpc.impl
  cloud:
    # 不配置默认是订阅所有服务，但是这个是服务提供者，不需要订阅其他服务，所以这里就配置一个自己好了，以免订阅所有服务
    subscribed-services: ${spring.application.name}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn_member?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true
    username: root
    password: 123456

mybatis-plus:
  global-config:
    banner: false