# 以下文件放Nacos Config，Data ID：learn-admin.yaml，Group：LEARN_GROUP
server:
  port: 8800

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.meeleet.learn.ops.controller
  cloud:
    subscribed-services: learn-sysms,learn-ums,learn-feign-ums
  consumer:
    check: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url:
      path: /swagger-ui.html
    oauth:
      client-id: client
      client-secret: 123456
      scopes: all
  oauth-flow:
    token-url: http://localhost:9999/learn-auth/oauth/token
  server-url: ${gateway.base-url}/${spring.application.name}
  show-actuator: true
  packages-to-scan: com.meeleet.learn.ops.controller,com.meeleet.learn.common.file.controller
  info:
    version: 1.0.0

# MinIO 分布式文件系统
minio:
  # 自定义域名(非必须)，Nginx配置反向代理转发文件路径
  custom-domain:
  # 默认的桶名称(非必须)，每个微服务有单独的默认存储桶，建议具体聚合层服务覆盖此配置
  default-bucket: ${spring.application.name}