# 以下文件放Nacos Config，Data ID：learn-admin.yaml，Group：LEARN_GROUP
server:
  port: 8800

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    port: -1
  cloud:
    subscribed-services: learn-ums,learn-feign-ums
  consumer:
    check: false
demo:
  name: hello1134xxx