# 所有项目公共的配置放这里
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: GMT+8


# 用于解决openapi3，网关聚合微服务文档时，server跨域问题，如果server的地址用网关来转发的就可以解决跨域问题了
gateway:
  base-url: http://localhost:9999